server:
  port: ${PORT:8080}
#  port: 8066
spring:
  application:
    name: crm
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:5432/crm_system
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
thymeleaf:
  cache: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
upload:
  dir: files/logos
app:
  pagination:
    page-size: 5
