server:
  port: 8066
spring:
  application:
    name: crm
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/crm_system
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
