server:
#  port: ${PORT:8080}
  port: 8066
spring:
  application:
    name: crm
  datasource:
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:5432/crm_system
#    username: postgres
#    password: admin
#    url: ${SPRING_DATASOURCE_URL}
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
thymeleaf:
  cache: false
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
upload:
  dir: files/logos
app:
  pagination:
    page-size: 5
