server:
  port: ${PORT:8080}
#  port: 8066
spring:
  application:
    name: crm
  datasource:
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    username: crm_system_59u0_user
#    password: XpxNsoQIRYHnF8FdbQ0lTXmrziQbWDX7
#    url: jdbc:postgresql://localhost:5432/crm_system
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
thymeleaf:
  cache: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
upload:
  dir: files/logos
app:
  pagination:
    page-size: 5
